namespace FEN
{

    using ARX;
    using FEN;

    //Auto-Generated by FEN_CustomEditor_Encounter.cs

    public static partial class CombatEncounters
    {
        public static class EncounterList
        {
            public static FEN_Encounter DebugBattle
            {
                get
                {
                    return FEN.Loading.LoadEncounter("debugBattle");
                }
            }

        }
    }
}